### ISSUE TITLE
load_outputs method does not handle partially complete jobs gracefully

### ISSUE THREAD

**Issue by craigyk** [cryoem-uoft/cryosparc-tools#29]
I was working through the example in the docs for plotting a trajectory through the latent space and was having problems running the example.  Traced it down to some of the outputs get updated by version while others do not, so the method tries to index into an empty version list for outputs that haven't yet saved a version.

For the 3DFlex training, it seems only `components_mode_?` outputs get updated per version.  I think the method could be improved to automagically exclude empty results (the code below isn't tested, just meant to show filtering empty outputs):

`
version = version if version else -1
metafiles = [r["metafiles"] for r in results]
metafiles = [m for m in metafiles if len(m)]
metafiles = [m[version] for m in metafiles]
metafiles = set(metafiles)
`

 or the docs can be updated to use the `slots` argument:

`particles = job.load_output('particles', ['components_mode_0', 'components_mode_1'])`

**Comment by nfrasser** [comment]
Fixed in v4.3.0
